# Generated by Django 5.2.7 on 2025-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_text', models.CharField(help_text="El comando exacto que el usuario debe decir. Ej: 'Activar detección de obstáculos'", max_length=255, verbose_name='Texto del Comando a Decir')),
                ('explanation_text', models.TextField(blank=True, help_text="Una breve descripción de lo que hace el comando (para la sección 'Ver ejemplos').", verbose_name='Explicación del Comando')),
                ('order', models.PositiveIntegerField(default=0, help_text='El orden en que aparecerá el ejercicio (0 primero, 1 después, etc.).', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Ejercicio de Entrenamiento',
                'verbose_name_plural': 'Ejercicios de Entrenamiento',
                'ordering': ['order'],
            },
        ),
    ]
